### ISSUE TITLE
Add Configurable Master Interface for NetworkAttachmentDefinition in Helm Chart

### ISSUE THREAD

**Issue by bl4ckj4c** [fluidos-project/node#123]
Hi everyone,

I noticed that the NetworkAttachmentDefinition for macvlan-conf in the Network Manager defaults to using eth0 as the master interface. However, not all clusters use eth0 as the default network interface on their nodes. It would be helpful to add a configurable value in the values.yaml file of the Helm chart, allowing users to specify the desired master interface during installation. This change would enhance compatibility across different environments.

**Comment by LorenzoMoro** [comment]
Hi @bl4ckj4c,
you're right, we worked with kind env in mind but as a matter of fact eth0 isn't standard at all (especially on Ubuntu 24).
We'll release a patch to address this issue.
