### ISSUE TITLE
Peering Candidate consumer side reservation logic

### ISSUE THREAD

**Issue by andreacv98** [fluidos-project/node#32]
Hello everyone,

With this issue I would like to address an overlapping behavior. The reservation of the Peering Candidate on the consumer cluster is highlighted by a boolean flag in its specifications. My suggestion would be to move this logic to the creation of the Reservation resource on the consumer side.

In fact, the Reservation is a resource that gives information about the reservation status of the flavor on the consumer side, as well as the fact that a peering candidate has been chosen to be reserved by a solver.

We can unbind the entire reservation logic from the discovery process to the reservation process.

Your attention to this matter and contributions toward resolution are greatly appreciated.

Best regards,
Andrea

**Comment by fracappa** [comment]
This issue has been resolved by PR #41.
