### ISSUE TITLE
Containerd support

### ISSUE THREAD

**Issue by dimitrisbro** [fluidos-project/node#72]
Hi, 

This issue is to propose the inclusion of **containerd** as a container runtime alternative to docker.

This will probably require the inclusion of **nerdctl** CLI to handle the containerd in a Docker-compatible manner.

What do you think about that?

Thanks,
Dimitris

**Comment by fracappa** [comment]
Hi @dimitrisbro .

I don't understand what you're proposing.

Have you already used the FLUIDOS Node on a K8s cluster running with containerd? Did you have some problem?
You should not have conflicts running containerd, but if you have any specific problem please report it so we can take a deeper look into it.

Thanks,
Francesco
