### ISSUE TITLE
Adding Contributing Section in the Repo Documentation

### ISSUE THREAD

**Issue by fracappa** [fluidos-project/node#77]
Hi team,

I would like to suggest adding a Contribution section to our project documentation. This section would provide guidelines and instructions for external users on how they can contribute to the project.

Here are a few points that this section could cover:

-  **How to Submit Contributions**: Instructions on how to fork the repository, create a branch, and submit a pull request.
- **Coding Standards**: Guidelines on the coding style and standards we follow.
- **Issue Reporting**: How to report bugs or suggest new features.
- **Development Workflow**: An overview of our development process, including how we handle new features, bug fixes, and code reviews.
- **Testing**: Information on how to run tests and the testing frameworks we use.
-  **Documentation**: Guidelines for updating or adding new documentation.

Adding this section could help facilitate contributions and make it easier for new contributors to get involved.

Thank you for considering this suggestion.

Best regards,
Francesco

**Comment by frisso** [comment]
That's nice, @fracappa !
Any suggestion / project to "copy" (and adapt, of course) this file from?

**Comment by fracappa** [comment]
Yes I do have a few suggestions. @frisso 

There are some similiarities with `Liqo`, as we usually test features and bug fixes in the same way.

I also come across `Falco` repo which share some similiarities with us.

I think we can take inspiration from this two, but any other suggestion/comment are highly appreciated.
